//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankManagementSystem
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BloodDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BloodDetail()
        {
            this.RequestBloods = new HashSet<RequestBlood>();
        }
    
        public int BloodId { get; set; }
        [Display(Name ="Blood Group")]
        [Required(ErrorMessage ="Field is required")]
        public string BloodName { get; set; }
        [Display(Name = "Details")]
        [Required(ErrorMessage = "Field is required")]
        public string BloodDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestBlood> RequestBloods { get; set; }
    }
}
