//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankManagementSystem
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Donor
    {
        //public int DonorId { get; set; }
        //[Display(Name = " Donor Name")]
        //[Required(ErrorMessage = "Field is required")]

        //public string DonorName { get; set; }
        //[Required(ErrorMessage = "Field is required")]
        //public int GenderId { get; set; }
        //[Display(Name = "Birth Date")]

        //public System.DateTime Birth_Date { get; set; }
        //[Display(Name = "Contact No")]
        //[Required(ErrorMessage = "Field is required")]
        //public string ContactNo { get; set; }
        //[Display(Name = "Email")]

        //public string Email { get; set; }
        //[Display(Name = "Donation Date")]

        //public System.DateTime Donation_Date { get; set; }
        //[Display(Name = "Address")]
        //public string Address { get; set; }
        //public int BloodListId { get; set; }
        //[Required(ErrorMessage = "Field is required")]
        //public virtual BloodStock BloodStock { get; set; }
        //[Required(ErrorMessage = "Field is required")]
        //public virtual Gender Gender { get; set; }
        public int DonorId { get; set; }
        [Display(Name = " Donor Name")]
        [Required(ErrorMessage = "Field is required")]
        public string DonorName { get; set; }
        public int GenderId { get; set; }
        [Required(ErrorMessage = "Field is required")]
        [Display(Name = "Birth Date")]
        public System.DateTime Birth_Date { get; set; }
        [Required(ErrorMessage = "Field is required")]
        [Display(Name = "Contact No.")]
        public string ContactNo { get; set; }
       
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "E-mail is not valid")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Field is required")]
        [Display(Name = "Donation Date")]
        public System.DateTime Donation_Date { get; set; }
        [Required(ErrorMessage = "Field is required")]
        [Display(Name = "Address")]
        public string Address { get; set; }
        public int BloodListId { get; set; }
     
        [Display(Name = "Blood Group")]
        public virtual BloodStock BloodStock { get; set; }
        [Display(Name ="Gender")]
        
        public virtual Gender Gender { get; set; }
    }
}
