//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankManagementSystem
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int EmployeeId { get; set; }
        [Display(Name = " Name")]
        [Required(ErrorMessage = "Field is required")]
        public string Name { get; set; }
        [Display(Name = "Designtaion")]
        [Required(ErrorMessage = "Field is required")]
        public string Designation { get; set; }
        
        public string Gender { get; set; }
        [Required(ErrorMessage = "Field is required")]
        public string Age { get; set; }
        [Display(Name = "Contact no")]
        [Required(ErrorMessage = "Field is required")]
        public string ContactNo { get; set; }
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "E-mail is not valid")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Field is required")]
        public string Address { get; set; }
        [Display(Name = "Join Date")]
        [Required(ErrorMessage = "Field is required")]
        public System.DateTime Join_Date { get; set; }
      
        public Nullable<int> BloodListId { get; set; }
        [Display(Name = "Blood Group")]
    
        public virtual BloodStock BloodStock { get; set; }
    }
}
