//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankManagementSystem
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Patient
    {
        public int PatientID { get; set; }
        [Display(Name ="Patient Name")]
        [Required(ErrorMessage = "Field is required")]
        public string PatientName { get; set; }
        public int GenderId { get; set; }
        [Display(Name = "Birth Date")]
        [Required(ErrorMessage = "Field is required")]

        public System.DateTime Birth_Date { get; set; }
        [Display(Name = "Contact No")]
        [Required(ErrorMessage = "Field is required")]

        public string ContactNo { get; set; }
        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage ="Field is required")]

        public string Email { get; set; }
        [Display(Name = "Address")]
        [Required(ErrorMessage = "Field is required")]
        public string Address { get; set; }
        public int BloodListId { get; set; }
        [Display(Name ="Blood Group")]

        public virtual BloodStock BloodStock { get; set; }
        [Display(Name ="Gender")]
        public virtual Gender Gender { get; set; }
    }
}
