//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankManagementSystem
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RequestBlood
    {

        public int RequestId { get; set; }
        [Display(Name ="Name")]
        [Required(ErrorMessage ="Field is required")]
        public string Name { get; set; }
        public int BloodListId { get; set; }
        public int BloodId { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        [Display(Name = "Age")]
        [Required(ErrorMessage = "Field is required")]
        public string Age { get; set; }
        [Display(Name = "Name")]
        [Required(ErrorMessage = "Field is required")]
        public string Gender { get; set; }
        [Display(Name = "Address")]
        [Required(ErrorMessage = "Field is required")]
        public string Address { get; set; }
        [Display(Name = "Contact No.")]
        [Required(ErrorMessage = "Field is required")]
        public string ContactNo { get; set; }
        [Display(Name = " Blood Details")]
       
        public virtual BloodDetail BloodDetail { get; set; }
        [Display(Name ="Blood Group")]
        public virtual BloodStock BloodStock { get; set; }
    }
}
